### ISSUE TITLE
Unknown type name '__declspec'

### ISSUE THREAD

**Issue by lalamm** [pppoe/WhatsThis-iOS#1]
Thanks for a great example app! But when I compile it with the new xcode 7.3 I get the following error
Unknown type name '__declspec'.

How can I solve it?

**Comment by pppoe** [comment]
@lalamm Thanks for pointing out this. I am able to reproduce this after updating to Xcode 7.3. The master branch is updated. You can also fix it by adding "-fms-extensions" in Build Settings -> Apple LLVM 7.1 - Custom Compiler Flags -> Other Warning Flags. 

[Reference](http://clang.llvm.org/docs/AttributeReference.html#id52)

**Comment by lalamm** [comment]
Great, thank you!
